/* NETWORK SETUP */

#define SERVER_ADDRESS "127.0.0.1"
#define SERVER_PORT 2048

/* BASE VARIABLES CONFIGURATIONS */

#define TRUE 1
#define FALSE 0

/* APP SETUP */

#define MAX_CONNECTIONS 16

#define MAX_SESSIONS 6

#define MAX_CLIENTS_PER_SESSION 2
